export * from './candidatos.controller';
export * from './cargo.controller';
export * from './carrera.controller';
export * from './usuarios.controller';
export * from './institutions.controller';
export * from './students.controller';
export * from './subjects.controller';
export * from './information-teachers.controller';
export * from './lists.controllers';
