export * from './candiatos-list.entity';
export * from './cargo.entity';
export * from './carrera.entity';
export * from './usuario.entity';
export * from './information-teacher.entity';
export * from './institution.entity';
export * from './student.entity';
export * from './subject.entity';
export * from './list.entity';