export * from './candidatos-list.entity';
export * from './cargo.entity';
export * from './carrera.entity';
export * from './configuration.entity';
export * from './information-teacher.entity';
export * from './institution.entity';
export * from './list.entity';
export * from './tipoLista';
export * from './periodo.entity';
export * from './roles_usuario.entity';
export * from './roles.entity';
export * from './tarea.entity';
export * from './tipoUsuario';
export * from './usuario.entity';
export * from './votos.entity';
export * from './cronograma.entity'
